on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: octokit/graphql-action@v2.x
      id: get_latest_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        query: |
          query release($owner:String!,$repo:String!) {
            repository(owner:$owner,name:$repo) {
              releases(first:1) {
                nodes {
                  name
                  createdAt
                  tagName
                  description
                }
              }
            }
          }
        owner: ${{ github.event.repository.owner.name }}
        repo: ${{ github.event.repository.name }}
    - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
